/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202310241605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_Head_Unit_STUB_HPP_
#define V0_COMMONAPI_Head_Unit_STUB_HPP_

#include <functional>
#include <sstream>




#include <v0/commonapi/HeadUnit.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service HeadUnit. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class HeadUnitStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual HeadUnit {
 public:
    ///Notifies all remote listeners about a change of value of the attribute lightMode.
    virtual void fireLightModeAttributeChanged(const bool &lightMode) = 0;
    ///Notifies all remote listeners about a change of value of the attribute unit.
    virtual void fireUnitAttributeChanged(const std::string &unit) = 0;
    ///Notifies all remote listeners about a change of value of the attribute metadata.
    virtual void fireMetadataAttributeChanged(const ::v0::commonapi::HeadUnit::MetaData &metadata) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockLightModeAttribute(bool _lockAccess) {
        if (_lockAccess) {
            lightModeMutex_.lock();
        } else {
            lightModeMutex_.unlock();
        }
    }
    void lockUnitAttribute(bool _lockAccess) {
        if (_lockAccess) {
            unitMutex_.lock();
        } else {
            unitMutex_.unlock();
        }
    }
    void lockMetadataAttribute(bool _lockAccess) {
        if (_lockAccess) {
            metadataMutex_.lock();
        } else {
            metadataMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex lightModeMutex_;
    std::recursive_mutex unitMutex_;
    std::recursive_mutex metadataMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for HeadUnit.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class HeadUnitStubRemoteEvent
{
public:
    virtual ~HeadUnitStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service HeadUnit to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class HeadUnitStub
    : public virtual CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>
{
public:

    virtual ~HeadUnitStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 3);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute lightMode
    virtual const bool &getLightModeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireLightModeAttributeChanged(bool _value) {
    auto stubAdapter = CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireLightModeAttributeChanged(_value);
    }
    void lockLightModeAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockLightModeAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute unit
    virtual const std::string &getUnitAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireUnitAttributeChanged(std::string _value) {
    auto stubAdapter = CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireUnitAttributeChanged(_value);
    }
    void lockUnitAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockUnitAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute metadata
    virtual const ::v0::commonapi::HeadUnit::MetaData &getMetadataAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireMetadataAttributeChanged(::v0::commonapi::HeadUnit::MetaData _value) {
    auto stubAdapter = CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireMetadataAttributeChanged(_value);
    }
    void lockMetadataAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockMetadataAttribute(_lockAccess);
    }


    using CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<HeadUnitStubAdapter, HeadUnitStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef HeadUnitStubRemoteEvent RemoteEventType;
    typedef ::v0::commonapi::HeadUnit StubInterface;
};

} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_Head_Unit_STUB_HPP_
